### PR TITLE
Update brailleHandler.class.php

### PR DESCRIPTION
**Pull request by HoldOffHunger**
Corrected the mappings for: h, 8, capital, ?, both parens, forward slash, backward slash

Source: https://www.pharmabraille.com/pharmaceutical-braille/the-braille-alphabet/

Also, hey, could you add an open source license?  Maybe something permissive like BSD-y?  You have some good code and I've been updating it just a smidge: https://3v4l.org/XXrDn

_Happy World Braille Day!_

### CODE REVIEW

**Comment by wimulkeman** [comment]
@HoldOffHunger Thanks for contributing. Turns out I've used the old capital notation of two dots for this time, but it was changed for already some time now.

**Comment by wimulkeman** [comment]
I've added a license and updated the texts to English instead of Dutch.

**Comment by HoldOffHunger** [comment]
That's awesome, thanks so much!

**Comment by HoldOffHunger** [comment]
Just wanted to say thanks again for such an awesome project!  I finally got around to building my own release of your project (with optional modes for UTF-8 chars and ASCII-mode) here: https://github.com/HoldOffHunger/english-to-braille-php

I tried to give gratuitous praise for your project, both in the README.MD and in comments in the code.  I'll probably go over it again just to check if I missed anything.

Thanks again, you rock!

**Pull request merged**
